#!/bin/sh

### Capturing uniqname of user currently logging in to system
loggedInUser=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }')

echo "Users deleted:"
echo " "
for home in $(ls /Users | grep -v -e $loggedInUser -e admin -e Shared -e root -e loginwindow)
do
    echo $home
    sysadminctl -deleteUser $home
    #sysadminctl -adminUser admin -adminPassword admin_pw -deleteUser $home 
done
echo " "
echo "Process complete."
